enum {
	iAPGeneralLingo = 0x00,
	iAPMicrophoneLingo = 0x01,
	iAPSimpleRemoteLingo = 0x02,
	iAPDisplayRemoteLingo = 0x03,
	iAPExtendedInterfaceLingo = 0x04,
	iAPAccessoryPowerLingo = 0x05,
	iAPUSBHostModeLingo = 0x06,
	iAPRFTunerLingo = 0x07,
	iAPAccessoryEqualizerLingo = 0x08,
	iAPSportsLingo = 0x09,
	iAPDigitalAudioLingo = 0x0A,
	iAPTestLingo = 0x0B,
	iAPStorageLingo = 0x0C,
	iAPiPodOutLingo = 0x0D,
	iAPLocationLingo = 0x0E,
};

enum {
	iAPGeneralLingoRequestIdentifyCommand = 0x00,
	iAPGeneralLingoIdentifyCommand = 0x01,
	iAPGeneralLingoiPodAckCommand = 0x02,
	iAPGeneralLingoRequestExtendedInterfaceModeCommand = 0x03,
	iAPGeneralLingoReturnExtendedInterfaceModeCommand = 0x04,
	iAPGeneralLingoEnterExtendedInterfaceModeCommand = 0x05,
	iAPGeneralLingoExitExtendedInterfaceModeCommand = 0x06,
	iAPGeneralLingoRequestiPodNameCommand = 0x07,
	iAPGeneralLingoReturniPodNameCommand = 0x08,
	iAPGeneralLingoRequestiPodSoftwareVersionCommand = 0x09,
	iAPGeneralLingoReturniPodSoftwareVersionCommand = 0x0A,
	iAPGeneralLingoRequestiPodSerialNumCommand = 0x0B,
	iAPGeneralLingoReturniPodSerialNumCommand = 0x0C,
	iAPGeneralLingoRequestiPodModelNumCommand = 0x0D,
	iAPGeneralLingoReturniPodModelNumCommand = 0x0E,
	iAPGeneralLingoRequestLingoProtocolVersionCommand = 0x0F,
	iAPGeneralLingoReturnLingoProtocolVersionCommand = 0x10,
	iAPGeneralLingoRequestTransportMaxPayloadSizeCommand = 0x11,
	iAPGeneralLingoReturnTransportMaxPayloadSizeCommand = 0x12,
	iAPGeneralLingoIdentifyDeviceLingoesCommand = 0x13,
	iAPGeneralLingoGetAccessoryAuthenticationInfoCommand = 0x14,
	iAPGeneralLingoRetAccessoryAuthenticationInfoCommand = 0x15,
	iAPGeneralLingoAckAccessoryAuthenticationInfoCommand = 0x16,
	iAPGeneralLingoGetAccessoryAuthenticationSignatureCommand = 0x17,
	iAPGeneralLingoRetAccessoryAuthenticationSignatureCommand = 0x18,
	iAPGeneralLingoAckAccessoryAuthenticationStatusCommand = 0x19,
	iAPGeneralLingoGetiPodAuthenticationInfoCommand = 0x1A,
	iAPGeneralLingoRetiPodAuthenticationInfoCommand = 0x1B,
	iAPGeneralLingoAckiPodAuthenticationInfoCommand = 0x1C,
	iAPGeneralLingoGetiPodAuthenticationSignatureCommand = 0x1D,
	iAPGeneralLingoRetiPodAuthenticationSignatureCommand = 0x1E,
	iAPGeneralLingoAckiPodAuthenticationStatusCommand = 0x1F,
	iAPGeneralLingoNotifyiPodStateChangeCommand = 0x23,
	iAPGeneralLingoGetiPodOptionsCommand = 0x24,
	iAPGeneralLingoRetiPodOptionsCommand = 0x25,
	iAPGeneralLingoGetAccessoryInfoCommand = 0x27,
	iAPGeneralLingoRetAccessoryInfoCommand = 0x28,
	iAPGeneralLingoGetiPodPreferencesCommand = 0x29,
	iAPGeneralLingoRetiPodPreferencesCommand = 0x2A,
	iAPGeneralLingoSetiPodPreferencesCommand = 0x2B,
	iAPGeneralLingoGetUIModeCommand = 0x35,
	iAPGeneralLingoRetUIModeCommand = 0x36,
	iAPGeneralLingoSetUIModeCommand = 0x37,
	iAPGeneralLingoStartIDPSCommand = 0x38,
	iAPGeneralLingoSetFIDTokenValuesCommand = 0x39,
	iAPGeneralLingoAckFIDTokenValuesCommand = 0x3A,
	iAPGeneralLingoEndIDPSCommand = 0x3B,
	iAPGeneralLingoIDPSStatusCommand = 0x3C,
	iAPGeneralLingoOpenDataSessionForProtocolCommand = 0x3F,
	iAPGeneralLingoCloseDataSessionCommand = 0x40,
	iAPGeneralLingoAccessoryAckCommand = 0x41,
	iAPGeneralLingoAccessoryDataTransferCommand = 0x42,
	iAPGeneralLingoiPodDataTransferCommand = 0x43,
	iAPGeneralLingoSetAccessoryStatusNotificationCommand = 0x46,
	iAPGeneralLingoRetAccessoryStatusNotificationCommand = 0x47,
	iAPGeneralLingoAccessoryStatusNotificationCommand = 0x48,
	iAPGeneralLingoSetEventNotificationCommand = 0x49,
	iAPGeneralLingoiPodNotificationCommand = 0x4A,
	iAPGeneralLingoGetiPodOptionsForLingoCommand = 0x4B,
	iAPGeneralLingoRetiPodOptionsForLingoCommand = 0x4C,
	iAPGeneralLingoGetEventNotificationCommand = 0x4D,
	iAPGeneralLingoRetEventNotificationCommand = 0x4E,
	iAPGeneralLingoGetSupportedEventNotificationCommand = 0x4F,
	iAPGeneralLingoCancelCommandCommand = 0x50,
	iAPGeneralLingoRetSupportedEventNotificationCommand = 0x51,
	iAPGeneralLingoSetAvailableCurrentCommand = 0x54,
	iAPGeneralLingoSetInternalBatteryChargingStateCommand = 0x56,
	iAPGeneralLingoRequestApplicationLaunchCommand = 0x64,
	iAPGeneralLingoGetNowPlayingApplicationBundleNameCommand = 0x65,
	iAPGeneralLingoRetNowPlayingApplicationBundleNameCommand = 0x66,
	iAPGeneralLingoGetLocalizationInfoCommand = 0x67,
	iAPGeneralLingoRetLocalizationInfoCommand = 0x68,
	iAPGeneralLingoRequestWiFiConnectionInfoCommand = 0x69,
	iAPGeneralLingoWiFiConnectionInfoCommand = 0x6A,
	iAPGeneralLingoDetectSequenceCommand = 0xEE,
};

enum {
	iAPMicrophoneLingoBeginRecordCommand = 0x00,
	iAPMicrophoneLingoEndRecordCommand = 0x01,
	iAPMicrophoneLingoBeginPlaybackCommand = 0x02,
	iAPMicrophoneLingoEndPlaybackCommand = 0x03,
	iAPMicrophoneLingoAccessoryAckCommand = 0x04,
	iAPMicrophoneLingoGetAccessoryAckCommand = 0x05,
	iAPMicrophoneLingoiPodModeChangeCommand = 0x06,
	iAPMicrophoneLingoGetAccessoryCapsCommand = 0x07,
	iAPMicrophoneLingoRetAccessoryCapsCommand = 0x08,
	iAPMicrophoneLingoGetDevCtrlCommand = 0x09,
	iAPMicrophoneLingoRetDevCtrlCommand = 0x0A,
	iAPMicrophoneLingoSetDevCtrlCommand = 0x0B,
};

enum {
	iAPSimpleRemoteLingoContextButtonStatusCommand = 0x00,
	iAPSimpleRemoteLingoiPodAckCommand = 0x01,
	iAPSimpleRemoteLingoImageButtonStatusCommand = 0x02,
	iAPSimpleRemoteLingoVideoButtonStatusCommand = 0x03,
	iAPSimpleRemoteLingoAudioButtonStatusCommand = 0x04,
	iAPSimpleRemoteLingoiPodOutButtonStatusCommand = 0x0B,
	iAPSimpleRemoteLingoRotationInputStatusCommand = 0x0C,
	iAPSimpleRemoteLingoRadioButtonStatusCommand = 0x0D,
	iAPSimpleRemoteLingoCameraButtonStatusCommand = 0x0E,
	iAPSimpleRemoteLingoRegisterDescriptorCommand = 0x0F,
	iAPSimpleRemoteLingoiPodHIDReportCommand = 0x10,
	iAPSimpleRemoteLingoAccessoryHIDReportCommand = 0x11,
	iAPSimpleRemoteLingoUnregisterDescriptorCommand = 0x12,
	iAPSimpleRemoteLingoVoiceOverEventCommand = 0x13,
	iAPSimpleRemoteLingoGetVoiceOverParameterCommand = 0x14,
	iAPSimpleRemoteLingoRetVoiceOverParameterCommand = 0x15,
	iAPSimpleRemoteLingoSetVoiceOverParameterCommand = 0x16,
	iAPSimpleRemoteLingoGetCurrentVoiceOverItemPropertyCommand = 0x17,
	iAPSimpleRemoteLingoRetCurrentVoiceOverItemPropertyCommand = 0x18,
	iAPSimpleRemoteLingoSetVoiceOverContextCommand = 0x19,
	iAPSimpleRemoteLingoVoiceOverParameterChangedCommand = 0x1A,
	iAPSimpleRemoteLingoAccessoryAckCommand = 0x81,
};

enum {
	iAPDisplayRemoteLingoiPodAckCommand = 0x00,
	iAPDisplayRemoteLingoGetCurrentEQProfileIndexCommand = 0x01,
	iAPDisplayRemoteLingoRetCurrentEQProfileIndexCommand = 0x02,
	iAPDisplayRemoteLingoSetCurrentEQProfileIndexCommand = 0x03,
	iAPDisplayRemoteLingoGetNumEQProfilesCommand = 0x04,
	iAPDisplayRemoteLingoRetNumEQProfilesCommand = 0x05,
	iAPDisplayRemoteLingoGetIndexedEQProfileNameCommand = 0x06,
	iAPDisplayRemoteLingoRetIndexedEQProfileNameCommand = 0x07,
	iAPDisplayRemoteLingoSetRemoteEventNotificationCommand = 0x08,
	iAPDisplayRemoteLingoRemoteEventNotificationCommand = 0x09,
	iAPDisplayRemoteLingoGetRemoteEventStatusCommand = 0x0A,
	iAPDisplayRemoteLingoRetRemoteEventStatusCommand = 0x0B,
	iAPDisplayRemoteLingoGetiPodStateInfoCommand = 0x0C,
	iAPDisplayRemoteLingoRetiPodStateInfoCommand = 0x0D,
	iAPDisplayRemoteLingoSetiPodStateInfoCommand = 0x0E,
	iAPDisplayRemoteLingoGetPlayStatusCommand = 0x0F,
	iAPDisplayRemoteLingoRetPlayStatusCommand = 0x10,
	iAPDisplayRemoteLingoSetCurrentPlayingTrackCommand = 0x11,
	iAPDisplayRemoteLingoGetIndexedPlayingTrackInfoCommand = 0x12,
	iAPDisplayRemoteLingoRetIndexedPlayingTrackInfoCommand = 0x13,
	iAPDisplayRemoteLingoGetNumPlayingTracksCommand = 0x14,
	iAPDisplayRemoteLingoRetNumPlayingTracksCommand = 0x15,
	iAPDisplayRemoteLingoGetArtworkFormatsCommand = 0x16,
	iAPDisplayRemoteLingoRetArtworkFormatsCommand = 0x17,
	iAPDisplayRemoteLingoGetTrackArtworkDataCommand = 0x18,
	iAPDisplayRemoteLingoRetTrackArtworkDataCommand = 0x19,
	iAPDisplayRemoteLingoGetPowerBatteryStateCommand = 0x1A,
	iAPDisplayRemoteLingoRetPowerBatteryStateCommand = 0x1B,
	iAPDisplayRemoteLingoGetSoundCheckStateCommand = 0x1C,
	iAPDisplayRemoteLingoRetSoundCheckStateCommand = 0x1D,
	iAPDisplayRemoteLingoSetSoundCheckStateCommand = 0x1E,
	iAPDisplayRemoteLingoGetTrackArtworkTimesCommand = 0x1F,
	iAPDisplayRemoteLingoRetTrackArtworkTimesCommand = 0x20,
	iAPDisplayRemoteLingoCreateGeniusPlaylistCommand = 0x21,
	iAPDisplayRemoteLingoIsGeniusAvailableForTrackCommand = 0x22,
};

enum {
	iAPExtendedInterfaceLingoiPodAckCommand = 0x0001,
	iAPExtendedInterfaceLingoGetCurrentPlayingTrackChapterInfoCommand = 0x0002,
	iAPExtendedInterfaceLingoReturnCurrentPlayingTrackChapterInfoCommand = 0x0003,
	iAPExtendedInterfaceLingoSetCurrentPlayingTrackChapterCommand = 0x0004,
	iAPExtendedInterfaceLingoGetCurrentPlayingTrackChapterPlayStatusCommand = 0x0005,
	iAPExtendedInterfaceLingoReturnCurrentPlayingTrackChapterPlayStatusCommand = 0x0006,
	iAPExtendedInterfaceLingoGetCurrentPlayingTrackChapterNameCommand = 0x0007,
	iAPExtendedInterfaceLingoReturnCurrentPlayingTrackChapterNameCommand = 0x0008,
	iAPExtendedInterfaceLingoGetAudiobookSpeedCommand = 0x0009,
	iAPExtendedInterfaceLingoReturnAudiobookSpeedCommand = 0x000A,
	iAPExtendedInterfaceLingoSetAudiobookSpeedCommand = 0x000B,
	iAPExtendedInterfaceLingoGetIndexedPlayingTrackInfoCommand = 0x000C,
	iAPExtendedInterfaceLingoReturnIndexedPlayingTrackInfoCommand = 0x000D,
	iAPExtendedInterfaceLingoGetArtworkFormatsCommand = 0x000E,
	iAPExtendedInterfaceLingoRetArtworkFormatsCommand = 0x000F,
	iAPExtendedInterfaceLingoGetTrackArtworkDataCommand = 0x0010,
	iAPExtendedInterfaceLingoRetTrackArtworkDataCommand = 0x0011,
	iAPExtendedInterfaceLingoRequestProtocolVersionCommand = 0x0012,
	iAPExtendedInterfaceLingoReturnProtocolVersionCommand = 0x0013,
	iAPExtendedInterfaceLingoRequestiPodNameCommand = 0x0014,
	iAPExtendedInterfaceLingoReturniPodNameCommand = 0x0015,
	iAPExtendedInterfaceLingoResetDBSelectionCommand = 0x0016,
	iAPExtendedInterfaceLingoSelectDBRecordCommand = 0x0017,
	iAPExtendedInterfaceLingoGetNumberCategorizedDBRecordsCommand = 0x0018,
	iAPExtendedInterfaceLingoReturnNumberCategorizedDBRecordsCommand = 0x0019,
	iAPExtendedInterfaceLingoRetrieveCategorizedDatabaseRecordsCommand = 0x001A,
	iAPExtendedInterfaceLingoReturnCategorizedDatabaseRecordCommand = 0x001B,
	iAPExtendedInterfaceLingoGetPlayStatusCommand = 0x001C,
	iAPExtendedInterfaceLingoReturnPlayStatusCommand = 0x001D,
	iAPExtendedInterfaceLingoGetCurrentPlayingTrackIndexCommand = 0x001E,
	iAPExtendedInterfaceLingoReturnCurrentPlayingTrackIndexCommand = 0x001F,
	iAPExtendedInterfaceLingoGetIndexedPlayingTrackTitleCommand = 0x0020,
	iAPExtendedInterfaceLingoReturnIndexedPlayingTrackTitleCommand = 0x0021,
	iAPExtendedInterfaceLingoGetIndexedPlayingTrackArtistNameCommand = 0x0022,
	iAPExtendedInterfaceLingoReturnIndexedPlayingTrackArtistNameCommand = 0x0023,
	iAPExtendedInterfaceLingoGetIndexedPlayingTrackAlbumNameCommand = 0x0024,
	iAPExtendedInterfaceLingoReturnIndexedPlayingTrackAlbumNameCommand = 0x0025,
	iAPExtendedInterfaceLingoSetPlayStatusChangeNotificationCommand = 0x0026,
	iAPExtendedInterfaceLingoPlayStatusChangeNotificationCommand = 0x0027,
	iAPExtendedInterfaceLingoPlayCurrentSelectionCommand = 0x0028,
	iAPExtendedInterfaceLingoPlayControlCommand = 0x0029,
	iAPExtendedInterfaceLingoGetTrackArtworkTimesCommand = 0x002A,
	iAPExtendedInterfaceLingoRetTrackArtworkTimesCommand = 0x002B,
	iAPExtendedInterfaceLingoGetShuffleCommand = 0x002C,
	iAPExtendedInterfaceLingoReturnShuffleCommand = 0x002D,
	iAPExtendedInterfaceLingoSetShuffleCommand = 0x002E,
	iAPExtendedInterfaceLingoGetRepeatCommand = 0x002F,
	iAPExtendedInterfaceLingoReturnRepeatCommand = 0x0030,
	iAPExtendedInterfaceLingoSetRepeatCommand = 0x0031,
	iAPExtendedInterfaceLingoSetDisplayImageCommand = 0x0032,
	iAPExtendedInterfaceLingoGetMonoDisplayImageLimitsCommand = 0x0033,
	iAPExtendedInterfaceLingoReturnMonoDisplayImageLimitsCommand = 0x0034,
	iAPExtendedInterfaceLingoGetNumPlayingTracksCommand = 0x0035,
	iAPExtendedInterfaceLingoReturnNumPlayingTracksCommand = 0x0036,
	iAPExtendedInterfaceLingoSetCurrentPlayingTrackCommand = 0x0037,
	iAPExtendedInterfaceLingoSelectSortDBRecordCommand = 0x0038,
	iAPExtendedInterfaceLingoGetColorDisplayImageLimitsCommand = 0x0039,
	iAPExtendedInterfaceLingoReturnColorDisplayImageLimitsCommand = 0x003A,
	iAPExtendedInterfaceLingoResetDBSelectionHierarchyCommand = 0x003B,
	iAPExtendedInterfaceLingoGetDBiTunesInfoCommand = 0x003C,
	iAPExtendedInterfaceLingoRetDBiTunesInfoCommand = 0x003D,
	iAPExtendedInterfaceLingoGetUIDTrackInfoCommand = 0x003E,
	iAPExtendedInterfaceLingoRetUIDTrackInfoCommand = 0x003F,
	iAPExtendedInterfaceLingoGetDBTrackInfoCommand = 0x0040,
	iAPExtendedInterfaceLingoRetDBTrackInfoCommand = 0x0041,
	iAPExtendedInterfaceLingoGetPBTrackInfoCommand = 0x0042,
	iAPExtendedInterfaceLingoRetPBTrackInfoCommand = 0x0043,
	iAPExtendedInterfaceLingoCreateGeniusPlaylistCommand = 0x0044,
	iAPExtendedInterfaceLingoRefreshGeniusPlaylistCommand = 0x0045,
	iAPExtendedInterfaceLingoIsGeniusAvailableForTrackCommand = 0x0047,
	iAPExtendedInterfaceLingoGetPlaylistInfoCommand = 0x0048,
	iAPExtendedInterfaceLingoRetPlaylistInfoCommand = 0x0049,
	iAPExtendedInterfaceLingoPrepareUIDListCommand = 0x004A,
	iAPExtendedInterfaceLingoPlayPreparedUIDListCommand = 0x004B,
	iAPExtendedInterfaceLingoGetArtworkTimesCommand = 0x004C,
	iAPExtendedInterfaceLingoRetArtworkTimesCommand = 0x004D,
	iAPExtendedInterfaceLingoGetArtworkDataCommand = 0x004E,
	iAPExtendedInterfaceLingoRetArtworkDataCommand = 0x004F,
};

enum {
	iAPAccessoryPowerLingoBeginHighPowerCommand = 0x02,
	iAPAccessoryPowerLingoEndHighPowerCommand = 0x03,
};

enum {
	iAPUSBHostModeLingoAccessoryAckCommand = 0x00,
	iAPUSBHostModeLingoGetUSBPowerStateCommand = 0x01,
	iAPUSBHostModeLingoRetUSBPowerStateCommand = 0x02,
	iAPUSBHostModeLingoSetUSBPowerStateCommand = 0x03,
	iAPUSBHostModeLingoNotifyUSBModeCommand = 0x04,
	iAPUSBHostModeLingoiPodAckCommand = 0x80,
	iAPUSBHostModeLingoGetiPodUSBModeCommand = 0x81,
	iAPUSBHostModeLingoRetiPodUSBModeCommand = 0x82,
	iAPUSBHostModeLingoSetiPodUSBModeCommand = 0x83,
};

enum {
	iAPRFTunerLingoAccessoryAckCommand = 0x00,
	iAPRFTunerLingoGetTunerCapsCommand = 0x01,
	iAPRFTunerLingoRetTunerCapsCommand = 0x02,
	iAPRFTunerLingoGetTunerCtrlCommand = 0x03,
	iAPRFTunerLingoRetTunerCtrlCommand = 0x04,
	iAPRFTunerLingoSetTunerCtrlCommand = 0x05,
	iAPRFTunerLingoGetTunerBandCommand = 0x06,
	iAPRFTunerLingoRetTunerBandCommand = 0x07,
	iAPRFTunerLingoSetTunerBandCommand = 0x08,
	iAPRFTunerLingoGetTunerFreqCommand = 0x09,
	iAPRFTunerLingoRetTunerFreqCommand = 0x0A,
	iAPRFTunerLingoSetTunerFreqCommand = 0x0B,
	iAPRFTunerLingoGetTunerModeCommand = 0x0C,
	iAPRFTunerLingoRetTunerModeCommand = 0x0D,
	iAPRFTunerLingoSetTunerModeCommand = 0x0E,
	iAPRFTunerLingoGetTunerSeekRssiCommand = 0x0F,
	iAPRFTunerLingoRetTunerSeekRssiCommand = 0x10,
	iAPRFTunerLingoSetTunerSeekRssiCommand = 0x11,
	iAPRFTunerLingoTunerSeekStartCommand = 0x12,
	iAPRFTunerLingoTunerSeekDoneCommand = 0x13,
	iAPRFTunerLingoGetTunerStatusCommand = 0x14,
	iAPRFTunerLingoRetTunerStatusCommand = 0x15,
	iAPRFTunerLingoGetStatusNotifyMaskCommand = 0x16,
	iAPRFTunerLingoRetStatusNotifyMaskCommand = 0x17,
	iAPRFTunerLingoSetStatusNotifyMaskCommand = 0x18,
	iAPRFTunerLingoStatusChangeNotifyCommand = 0x19,
	iAPRFTunerLingoGetRdsReadyStatusCommand = 0x1A,
	iAPRFTunerLingoRetRdsReadyStatusCommand = 0x1B,
	iAPRFTunerLingoGetRdsDataCommand = 0x1C,
	iAPRFTunerLingoRetRdsDataCommand = 0x1D,
	iAPRFTunerLingoGetRdsNotifyMaskCommand = 0x1E,
	iAPRFTunerLingoRetRdsNotifyMaskCommand = 0x1F,
	iAPRFTunerLingoSetRdsNotifyMaskCommand = 0x20,
	iAPRFTunerLingoRdsReadyNotifyCommand = 0x21,
	iAPRFTunerLingoGetHDProgramServiceCountCommand = 0x25,
	iAPRFTunerLingoRetHDProgramServiceCountCommand = 0x26,
	iAPRFTunerLingoGetHDProgramServiceCommand = 0x27,
	iAPRFTunerLingoRetHDProgramServiceCommand = 0x28,
	iAPRFTunerLingoSetHDProgramServiceCommand = 0x29,
	iAPRFTunerLingoGetHDDataReadyStatusCommand = 0x2A,
	iAPRFTunerLingoRetHDDataReadyStatusCommand = 0x2B,
	iAPRFTunerLingoGetHDDataCommand = 0x2C,
	iAPRFTunerLingoRetHDDataCommand = 0x2D,
	iAPRFTunerLingoGetHDDataNotifyMaskCommand = 0x2E,
	iAPRFTunerLingoRetHDDataNotifyMaskCommand = 0x2F,
	iAPRFTunerLingoSetHDDataNotifyMaskCommand = 0x30,
	iAPRFTunerLingoHDDataReadyNotifyCommand = 0x31,
};

enum {
	iAPAccessoryEqualizerLingoAccessoryAckCommand = 0x00,
	iAPAccessoryEqualizerLingoGetCurrentEQIndexCommand = 0x01,
	iAPAccessoryEqualizerLingoRetCurrentEQIndexCommand = 0x02,
	iAPAccessoryEqualizerLingoSetCurrentEQIndexCommand = 0x03,
	iAPAccessoryEqualizerLingoGetEQSettingCountCommand = 0x04,
	iAPAccessoryEqualizerLingoRetEQSettingCountCommand = 0x05,
	iAPAccessoryEqualizerLingoGetEQIndexNameCommand = 0x06,
	iAPAccessoryEqualizerLingoRetEQIndexNameCommand = 0x07,
};

enum {
	iAPSportsLingoAccessoryAckCommand = 0x00,
	iAPSportsLingoGetAccessoryVersionCommand = 0x01,
	iAPSportsLingoRetAccessoryVersionCommand = 0x02,
	iAPSportsLingoGetAccessoryCapsCommand = 0x03,
	iAPSportsLingoRetAccessoryCapsCommand = 0x04,
	iAPSportsLingoiPodAckCommand = 0x80,
	iAPSportsLingoGetiPodCapsCommand = 0x83,
	iAPSportsLingoRetiPodCapsCommand = 0x84,
	iAPSportsLingoGetUserIndexCommand = 0x85,
	iAPSportsLingoRetUserIndexCommand = 0x86,
	iAPSportsLingoGetUserDataCommand = 0x88,
	iAPSportsLingoRetUserDataCommand = 0x89,
	iAPSportsLingoSetUserDataCommand = 0x8A,
};

enum {
	iAPDigitalAudioLingoAccessoryAckCommand = 0x00,
	iAPDigitalAudioLingoiPodAckCommand = 0x01,
	iAPDigitalAudioLingoGetAccessorySampleRateCapsCommand = 0x02,
	iAPDigitalAudioLingoRetAccessorySampleRateCapsCommand = 0x03,
	iAPDigitalAudioLingoTrackNewAudioAttributesCommand = 0x04,
	iAPDigitalAudioLingoSetVideoDelayCommand = 0x05,
};

enum {
	iAPTestLingoGetModelStringCommand = 0x3C,
	iAPTestLingoRetModelStringCommand = 0x3D,
};

enum {
	iAPStorageLingoiPodAckCommand = 0x00,
	iAPStorageLingoGetiPodCapsCommand = 0x01,
	iAPStorageLingoRetiPodCapsCommand = 0x02,
	iAPStorageLingoRetiPodFileHandleCommand = 0x04,
	iAPStorageLingoWriteiPodFileDataCommand = 0x07,
	iAPStorageLingoCloseiPodFileCommand = 0x08,
	iAPStorageLingoGetiPodFreeSpaceCommand = 0x10,
	iAPStorageLingoRetiPodFreeSpaceCommand = 0x11,
	iAPStorageLingoOpeniPodFeatureFileCommand = 0x12,
	iAPStorageLingoAccessoryAckCommand = 0x80,
	iAPStorageLingoGetAccessoryCapsCommand = 0x81,
	iAPStorageLingoRetAccessoryCapsCommand = 0x82,
};

enum {
	iAPiPodOutLingoiPodAckCommand = 0x00,
	iAPiPodOutLingoGetiPodOutOptionsCommand = 0x01,
	iAPiPodOutLingoRetiPodOutOptionsCommand = 0x02,
	iAPiPodOutLingoSetiPodOutOptionsCommand = 0x03,
	iAPiPodOutLingoAccessoryStateChangeEventCommand = 0x04,
	iAPiPodOutLingoAccessoryVideoScreenInfoCommand = 0x06,
};

enum {
	iAPLocationLingoAccessoryAckCommand = 0x00,
	iAPLocationLingoGetAccessoryCapsCommand = 0x01,
	iAPLocationLingoRetAccessoryCapsCommand = 0x02,
	iAPLocationLingoGetAccessoryControlCommand = 0x03,
	iAPLocationLingoRetAccessoryControlCommand = 0x04,
	iAPLocationLingoSetAccessoryControlCommand = 0x05,
	iAPLocationLingoGetAccessoryDataCommand = 0x06,
	iAPLocationLingoRetAccessoryDataCommand = 0x07,
	iAPLocationLingoSetAccessoryDataCommand = 0x08,
	iAPLocationLingoAsyncAccessoryDataCommand = 0x09,
	iAPLocationLingoiPodAckCommand = 0x80,
};

