enum {
	RTGeneralLingo = 0x00,
	RTMicrophoneLingo = 0x01,
	RTSimpleRemoteLingo = 0x02,
	RTDisplayRemoteLingo = 0x03,
	RTExtendedInterfaceLingo = 0x04,
	RTAccessoryPowerLingo = 0x05,
	RTUSBHostModeLingo = 0x06,
	RTRFTunerLingo = 0x07,
	RTAccessoryEqualizerLingo = 0x08,
	RTSportsLingo = 0x09,
	RTDigitalAudioLingo = 0x0A,
	RTTestLingo = 0x0B,
	RTStorageLingo = 0x0C,
	RTiPodOutLingo = 0x0D,
	RTLocationLingo = 0x0E,
};

#define RT_CMD_LINGO_ID(lingo, id) ((lingo) << 16 | (id))
#define RT_CMD_LINGO(cmd_id) (((cmd_id) >> 16) & 0xffff)
#define RT_CMD_ID(cmd_id) ((cmd_id) & 0xffff)


enum {
	RTGeneralLingoRequestIdentify = RT_CMD_LINGO_ID(RTGeneralLingo, 0x00),
	RTGeneralLingoIdentify = RT_CMD_LINGO_ID(RTGeneralLingo, 0x01),
	RTGeneralLingoiPodAck = RT_CMD_LINGO_ID(RTGeneralLingo, 0x02),
	RTGeneralLingoRequestExtendedInterfaceMode = RT_CMD_LINGO_ID(RTGeneralLingo, 0x03),
	RTGeneralLingoReturnExtendedInterfaceMode = RT_CMD_LINGO_ID(RTGeneralLingo, 0x04),
	RTGeneralLingoEnterExtendedInterfaceMode = RT_CMD_LINGO_ID(RTGeneralLingo, 0x05),
	RTGeneralLingoExitExtendedInterfaceMode = RT_CMD_LINGO_ID(RTGeneralLingo, 0x06),
	RTGeneralLingoRequestiPodName = RT_CMD_LINGO_ID(RTGeneralLingo, 0x07),
	RTGeneralLingoReturniPodName = RT_CMD_LINGO_ID(RTGeneralLingo, 0x08),
	RTGeneralLingoRequestiPodSoftwareVersion = RT_CMD_LINGO_ID(RTGeneralLingo, 0x09),
	RTGeneralLingoReturniPodSoftwareVersion = RT_CMD_LINGO_ID(RTGeneralLingo, 0x0A),
	RTGeneralLingoRequestiPodSerialNum = RT_CMD_LINGO_ID(RTGeneralLingo, 0x0B),
	RTGeneralLingoReturniPodSerialNum = RT_CMD_LINGO_ID(RTGeneralLingo, 0x0C),
	RTGeneralLingoRequestiPodModelNum = RT_CMD_LINGO_ID(RTGeneralLingo, 0x0D),
	RTGeneralLingoReturniPodModelNum = RT_CMD_LINGO_ID(RTGeneralLingo, 0x0E),
	RTGeneralLingoRequestLingoProtocolVersion = RT_CMD_LINGO_ID(RTGeneralLingo, 0x0F),
	RTGeneralLingoReturnLingoProtocolVersion = RT_CMD_LINGO_ID(RTGeneralLingo, 0x10),
	RTGeneralLingoRequestTransportMaxPayloadSize = RT_CMD_LINGO_ID(RTGeneralLingo, 0x11),
	RTGeneralLingoReturnTransportMaxPayloadSize = RT_CMD_LINGO_ID(RTGeneralLingo, 0x12),
	RTGeneralLingoIdentifyDeviceLingoes = RT_CMD_LINGO_ID(RTGeneralLingo, 0x13),
	RTGeneralLingoGetAccessoryAuthenticationInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x14),
	RTGeneralLingoRetAccessoryAuthenticationInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x15),
	RTGeneralLingoAckAccessoryAuthenticationInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x16),
	RTGeneralLingoGetAccessoryAuthenticationSignature = RT_CMD_LINGO_ID(RTGeneralLingo, 0x17),
	RTGeneralLingoRetAccessoryAuthenticationSignature = RT_CMD_LINGO_ID(RTGeneralLingo, 0x18),
	RTGeneralLingoAckAccessoryAuthenticationStatus = RT_CMD_LINGO_ID(RTGeneralLingo, 0x19),
	RTGeneralLingoGetiPodAuthenticationInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x1A),
	RTGeneralLingoRetiPodAuthenticationInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x1B),
	RTGeneralLingoAckiPodAuthenticationInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x1C),
	RTGeneralLingoGetiPodAuthenticationSignature = RT_CMD_LINGO_ID(RTGeneralLingo, 0x1D),
	RTGeneralLingoRetiPodAuthenticationSignature = RT_CMD_LINGO_ID(RTGeneralLingo, 0x1E),
	RTGeneralLingoAckiPodAuthenticationStatus = RT_CMD_LINGO_ID(RTGeneralLingo, 0x1F),
	RTGeneralLingoNotifyiPodStateChange = RT_CMD_LINGO_ID(RTGeneralLingo, 0x23),
	RTGeneralLingoGetiPodOptions = RT_CMD_LINGO_ID(RTGeneralLingo, 0x24),
	RTGeneralLingoRetiPodOptions = RT_CMD_LINGO_ID(RTGeneralLingo, 0x25),
	RTGeneralLingoGetAccessoryInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x27),
	RTGeneralLingoRetAccessoryInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x28),
	RTGeneralLingoGetiPodPreferences = RT_CMD_LINGO_ID(RTGeneralLingo, 0x29),
	RTGeneralLingoRetiPodPreferences = RT_CMD_LINGO_ID(RTGeneralLingo, 0x2A),
	RTGeneralLingoSetiPodPreferences = RT_CMD_LINGO_ID(RTGeneralLingo, 0x2B),
	RTGeneralLingoGetUIMode = RT_CMD_LINGO_ID(RTGeneralLingo, 0x35),
	RTGeneralLingoRetUIMode = RT_CMD_LINGO_ID(RTGeneralLingo, 0x36),
	RTGeneralLingoSetUIMode = RT_CMD_LINGO_ID(RTGeneralLingo, 0x37),
	RTGeneralLingoStartIDPS = RT_CMD_LINGO_ID(RTGeneralLingo, 0x38),
	RTGeneralLingoSetFIDTokenValues = RT_CMD_LINGO_ID(RTGeneralLingo, 0x39),
	RTGeneralLingoAckFIDTokenValues = RT_CMD_LINGO_ID(RTGeneralLingo, 0x3A),
	RTGeneralLingoEndIDPS = RT_CMD_LINGO_ID(RTGeneralLingo, 0x3B),
	RTGeneralLingoIDPSStatus = RT_CMD_LINGO_ID(RTGeneralLingo, 0x3C),
	RTGeneralLingoOpenDataSessionForProtocol = RT_CMD_LINGO_ID(RTGeneralLingo, 0x3F),
	RTGeneralLingoCloseDataSession = RT_CMD_LINGO_ID(RTGeneralLingo, 0x40),
	RTGeneralLingoAccessoryAck = RT_CMD_LINGO_ID(RTGeneralLingo, 0x41),
	RTGeneralLingoAccessoryDataTransfer = RT_CMD_LINGO_ID(RTGeneralLingo, 0x42),
	RTGeneralLingoiPodDataTransfer = RT_CMD_LINGO_ID(RTGeneralLingo, 0x43),
	RTGeneralLingoSetAccessoryStatusNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x46),
	RTGeneralLingoRetAccessoryStatusNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x47),
	RTGeneralLingoAccessoryStatusNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x48),
	RTGeneralLingoSetEventNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x49),
	RTGeneralLingoiPodNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x4A),
	RTGeneralLingoGetiPodOptionsForLingo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x4B),
	RTGeneralLingoRetiPodOptionsForLingo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x4C),
	RTGeneralLingoGetEventNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x4D),
	RTGeneralLingoRetEventNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x4E),
	RTGeneralLingoGetSupportedEventNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x4F),
	RTGeneralLingoCancelCommand = RT_CMD_LINGO_ID(RTGeneralLingo, 0x50),
	RTGeneralLingoRetSupportedEventNotification = RT_CMD_LINGO_ID(RTGeneralLingo, 0x51),
	RTGeneralLingoSetAvailableCurrent = RT_CMD_LINGO_ID(RTGeneralLingo, 0x54),
	RTGeneralLingoSetInternalBatteryChargingState = RT_CMD_LINGO_ID(RTGeneralLingo, 0x56),
	RTGeneralLingoRequestApplicationLaunch = RT_CMD_LINGO_ID(RTGeneralLingo, 0x64),
	RTGeneralLingoGetNowPlayingApplicationBundleName = RT_CMD_LINGO_ID(RTGeneralLingo, 0x65),
	RTGeneralLingoRetNowPlayingApplicationBundleName = RT_CMD_LINGO_ID(RTGeneralLingo, 0x66),
	RTGeneralLingoGetLocalizationInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x67),
	RTGeneralLingoRetLocalizationInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x68),
	RTGeneralLingoRequestWiFiConnectionInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x69),
	RTGeneralLingoWiFiConnectionInfo = RT_CMD_LINGO_ID(RTGeneralLingo, 0x6A),
	RTGeneralLingoDetectSequence = RT_CMD_LINGO_ID(RTGeneralLingo, 0xEE),
};

enum {
	RTMicrophoneLingoBeginRecord = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x00),
	RTMicrophoneLingoEndRecord = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x01),
	RTMicrophoneLingoBeginPlayback = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x02),
	RTMicrophoneLingoEndPlayback = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x03),
	RTMicrophoneLingoAccessoryAck = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x04),
	RTMicrophoneLingoGetAccessoryAck = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x05),
	RTMicrophoneLingoiPodModeChange = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x06),
	RTMicrophoneLingoGetAccessoryCaps = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x07),
	RTMicrophoneLingoRetAccessoryCaps = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x08),
	RTMicrophoneLingoGetDevCtrl = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x09),
	RTMicrophoneLingoRetDevCtrl = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x0A),
	RTMicrophoneLingoSetDevCtrl = RT_CMD_LINGO_ID(RTMicrophoneLingo, 0x0B),
};

enum {
	RTSimpleRemoteLingoContextButtonStatus = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x00),
	RTSimpleRemoteLingoiPodAck = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x01),
	RTSimpleRemoteLingoImageButtonStatus = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x02),
	RTSimpleRemoteLingoVideoButtonStatus = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x03),
	RTSimpleRemoteLingoAudioButtonStatus = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x04),
	RTSimpleRemoteLingoiPodOutButtonStatus = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x0B),
	RTSimpleRemoteLingoRotationInputStatus = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x0C),
	RTSimpleRemoteLingoRadioButtonStatus = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x0D),
	RTSimpleRemoteLingoCameraButtonStatus = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x0E),
	RTSimpleRemoteLingoRegisterDescriptor = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x0F),
	RTSimpleRemoteLingoiPodHIDReport = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x10),
	RTSimpleRemoteLingoAccessoryHIDReport = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x11),
	RTSimpleRemoteLingoUnregisterDescriptor = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x12),
	RTSimpleRemoteLingoVoiceOverEvent = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x13),
	RTSimpleRemoteLingoGetVoiceOverParameter = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x14),
	RTSimpleRemoteLingoRetVoiceOverParameter = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x15),
	RTSimpleRemoteLingoSetVoiceOverParameter = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x16),
	RTSimpleRemoteLingoGetCurrentVoiceOverItemProperty = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x17),
	RTSimpleRemoteLingoRetCurrentVoiceOverItemProperty = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x18),
	RTSimpleRemoteLingoSetVoiceOverContext = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x19),
	RTSimpleRemoteLingoVoiceOverParameterChanged = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x1A),
	RTSimpleRemoteLingoAccessoryAck = RT_CMD_LINGO_ID(RTSimpleRemoteLingo, 0x81),
};

enum {
	RTDisplayRemoteLingoiPodAck = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x00),
	RTDisplayRemoteLingoGetCurrentEQProfileIndex = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x01),
	RTDisplayRemoteLingoRetCurrentEQProfileIndex = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x02),
	RTDisplayRemoteLingoSetCurrentEQProfileIndex = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x03),
	RTDisplayRemoteLingoGetNumEQProfiles = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x04),
	RTDisplayRemoteLingoRetNumEQProfiles = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x05),
	RTDisplayRemoteLingoGetIndexedEQProfileName = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x06),
	RTDisplayRemoteLingoRetIndexedEQProfileName = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x07),
	RTDisplayRemoteLingoSetRemoteEventNotification = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x08),
	RTDisplayRemoteLingoRemoteEventNotification = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x09),
	RTDisplayRemoteLingoGetRemoteEventStatus = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x0A),
	RTDisplayRemoteLingoRetRemoteEventStatus = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x0B),
	RTDisplayRemoteLingoGetiPodStateInfo = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x0C),
	RTDisplayRemoteLingoRetiPodStateInfo = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x0D),
	RTDisplayRemoteLingoSetiPodStateInfo = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x0E),
	RTDisplayRemoteLingoGetPlayStatus = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x0F),
	RTDisplayRemoteLingoRetPlayStatus = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x10),
	RTDisplayRemoteLingoSetCurrentPlayingTrack = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x11),
	RTDisplayRemoteLingoGetIndexedPlayingTrackInfo = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x12),
	RTDisplayRemoteLingoRetIndexedPlayingTrackInfo = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x13),
	RTDisplayRemoteLingoGetNumPlayingTracks = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x14),
	RTDisplayRemoteLingoRetNumPlayingTracks = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x15),
	RTDisplayRemoteLingoGetArtworkFormats = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x16),
	RTDisplayRemoteLingoRetArtworkFormats = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x17),
	RTDisplayRemoteLingoGetTrackArtworkData = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x18),
	RTDisplayRemoteLingoRetTrackArtworkData = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x19),
	RTDisplayRemoteLingoGetPowerBatteryState = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x1A),
	RTDisplayRemoteLingoRetPowerBatteryState = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x1B),
	RTDisplayRemoteLingoGetSoundCheckState = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x1C),
	RTDisplayRemoteLingoRetSoundCheckState = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x1D),
	RTDisplayRemoteLingoSetSoundCheckState = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x1E),
	RTDisplayRemoteLingoGetTrackArtworkTimes = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x1F),
	RTDisplayRemoteLingoRetTrackArtworkTimes = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x20),
	RTDisplayRemoteLingoCreateGeniusPlaylist = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x21),
	RTDisplayRemoteLingoIsGeniusAvailableForTrack = RT_CMD_LINGO_ID(RTDisplayRemoteLingo, 0x22),
};

enum {
	RTExtendedInterfaceLingoiPodAck = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0001),
	RTExtendedInterfaceLingoGetCurrentPlayingTrackChapterInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0002),
	RTExtendedInterfaceLingoReturnCurrentPlayingTrackChapterInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0003),
	RTExtendedInterfaceLingoSetCurrentPlayingTrackChapter = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0004),
	RTExtendedInterfaceLingoGetCurrentPlayingTrackChapterPlayStatus = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0005),
	RTExtendedInterfaceLingoReturnCurrentPlayingTrackChapterPlayStatus = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0006),
	RTExtendedInterfaceLingoGetCurrentPlayingTrackChapterName = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0007),
	RTExtendedInterfaceLingoReturnCurrentPlayingTrackChapterName = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0008),
	RTExtendedInterfaceLingoGetAudiobookSpeed = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0009),
	RTExtendedInterfaceLingoReturnAudiobookSpeed = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x000A),
	RTExtendedInterfaceLingoSetAudiobookSpeed = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x000B),
	RTExtendedInterfaceLingoGetIndexedPlayingTrackInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x000C),
	RTExtendedInterfaceLingoReturnIndexedPlayingTrackInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x000D),
	RTExtendedInterfaceLingoGetArtworkFormats = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x000E),
	RTExtendedInterfaceLingoRetArtworkFormats = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x000F),
	RTExtendedInterfaceLingoGetTrackArtworkData = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0010),
	RTExtendedInterfaceLingoRetTrackArtworkData = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0011),
	RTExtendedInterfaceLingoRequestProtocolVersion = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0012),
	RTExtendedInterfaceLingoReturnProtocolVersion = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0013),
	RTExtendedInterfaceLingoRequestiPodName = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0014),
	RTExtendedInterfaceLingoReturniPodName = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0015),
	RTExtendedInterfaceLingoResetDBSelection = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0016),
	RTExtendedInterfaceLingoSelectDBRecord = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0017),
	RTExtendedInterfaceLingoGetNumberCategorizedDBRecords = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0018),
	RTExtendedInterfaceLingoReturnNumberCategorizedDBRecords = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0019),
	RTExtendedInterfaceLingoRetrieveCategorizedDatabaseRecords = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x001A),
	RTExtendedInterfaceLingoReturnCategorizedDatabaseRecord = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x001B),
	RTExtendedInterfaceLingoGetPlayStatus = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x001C),
	RTExtendedInterfaceLingoReturnPlayStatus = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x001D),
	RTExtendedInterfaceLingoGetCurrentPlayingTrackIndex = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x001E),
	RTExtendedInterfaceLingoReturnCurrentPlayingTrackIndex = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x001F),
	RTExtendedInterfaceLingoGetIndexedPlayingTrackTitle = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0020),
	RTExtendedInterfaceLingoReturnIndexedPlayingTrackTitle = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0021),
	RTExtendedInterfaceLingoGetIndexedPlayingTrackArtistName = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0022),
	RTExtendedInterfaceLingoReturnIndexedPlayingTrackArtistName = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0023),
	RTExtendedInterfaceLingoGetIndexedPlayingTrackAlbumName = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0024),
	RTExtendedInterfaceLingoReturnIndexedPlayingTrackAlbumName = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0025),
	RTExtendedInterfaceLingoSetPlayStatusChangeNotification = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0026),
	RTExtendedInterfaceLingoPlayStatusChangeNotification = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0027),
	RTExtendedInterfaceLingoPlayCurrentSelection = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0028),
	RTExtendedInterfaceLingoPlayControl = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0029),
	RTExtendedInterfaceLingoGetTrackArtworkTimes = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x002A),
	RTExtendedInterfaceLingoRetTrackArtworkTimes = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x002B),
	RTExtendedInterfaceLingoGetShuffle = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x002C),
	RTExtendedInterfaceLingoReturnShuffle = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x002D),
	RTExtendedInterfaceLingoSetShuffle = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x002E),
	RTExtendedInterfaceLingoGetRepeat = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x002F),
	RTExtendedInterfaceLingoReturnRepeat = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0030),
	RTExtendedInterfaceLingoSetRepeat = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0031),
	RTExtendedInterfaceLingoSetDisplayImage = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0032),
	RTExtendedInterfaceLingoGetMonoDisplayImageLimits = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0033),
	RTExtendedInterfaceLingoReturnMonoDisplayImageLimits = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0034),
	RTExtendedInterfaceLingoGetNumPlayingTracks = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0035),
	RTExtendedInterfaceLingoReturnNumPlayingTracks = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0036),
	RTExtendedInterfaceLingoSetCurrentPlayingTrack = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0037),
	RTExtendedInterfaceLingoSelectSortDBRecord = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0038),
	RTExtendedInterfaceLingoGetColorDisplayImageLimits = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0039),
	RTExtendedInterfaceLingoReturnColorDisplayImageLimits = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x003A),
	RTExtendedInterfaceLingoResetDBSelectionHierarchy = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x003B),
	RTExtendedInterfaceLingoGetDBiTunesInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x003C),
	RTExtendedInterfaceLingoRetDBiTunesInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x003D),
	RTExtendedInterfaceLingoGetUIDTrackInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x003E),
	RTExtendedInterfaceLingoRetUIDTrackInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x003F),
	RTExtendedInterfaceLingoGetDBTrackInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0040),
	RTExtendedInterfaceLingoRetDBTrackInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0041),
	RTExtendedInterfaceLingoGetPBTrackInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0042),
	RTExtendedInterfaceLingoRetPBTrackInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0043),
	RTExtendedInterfaceLingoCreateGeniusPlaylist = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0044),
	RTExtendedInterfaceLingoRefreshGeniusPlaylist = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0045),
	RTExtendedInterfaceLingoIsGeniusAvailableForTrack = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0047),
	RTExtendedInterfaceLingoGetPlaylistInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0048),
	RTExtendedInterfaceLingoRetPlaylistInfo = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x0049),
	RTExtendedInterfaceLingoPrepareUIDList = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x004A),
	RTExtendedInterfaceLingoPlayPreparedUIDList = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x004B),
	RTExtendedInterfaceLingoGetArtworkTimes = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x004C),
	RTExtendedInterfaceLingoRetArtworkTimes = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x004D),
	RTExtendedInterfaceLingoGetArtworkData = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x004E),
	RTExtendedInterfaceLingoRetArtworkData = RT_CMD_LINGO_ID(RTExtendedInterfaceLingo, 0x004F),
};

enum {
	RTAccessoryPowerLingoBeginHighPower = RT_CMD_LINGO_ID(RTAccessoryPowerLingo, 0x02),
	RTAccessoryPowerLingoEndHighPower = RT_CMD_LINGO_ID(RTAccessoryPowerLingo, 0x03),
};

enum {
	RTUSBHostModeLingoAccessoryAck = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x00),
	RTUSBHostModeLingoGetUSBPowerState = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x01),
	RTUSBHostModeLingoRetUSBPowerState = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x02),
	RTUSBHostModeLingoSetUSBPowerState = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x03),
	RTUSBHostModeLingoNotifyUSBMode = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x04),
	RTUSBHostModeLingoiPodAck = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x80),
	RTUSBHostModeLingoGetiPodUSBMode = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x81),
	RTUSBHostModeLingoRetiPodUSBMode = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x82),
	RTUSBHostModeLingoSetiPodUSBMode = RT_CMD_LINGO_ID(RTUSBHostModeLingo, 0x83),
};

enum {
	RTRFTunerLingoAccessoryAck = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x00),
	RTRFTunerLingoGetTunerCaps = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x01),
	RTRFTunerLingoRetTunerCaps = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x02),
	RTRFTunerLingoGetTunerCtrl = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x03),
	RTRFTunerLingoRetTunerCtrl = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x04),
	RTRFTunerLingoSetTunerCtrl = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x05),
	RTRFTunerLingoGetTunerBand = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x06),
	RTRFTunerLingoRetTunerBand = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x07),
	RTRFTunerLingoSetTunerBand = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x08),
	RTRFTunerLingoGetTunerFreq = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x09),
	RTRFTunerLingoRetTunerFreq = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x0A),
	RTRFTunerLingoSetTunerFreq = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x0B),
	RTRFTunerLingoGetTunerMode = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x0C),
	RTRFTunerLingoRetTunerMode = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x0D),
	RTRFTunerLingoSetTunerMode = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x0E),
	RTRFTunerLingoGetTunerSeekRssi = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x0F),
	RTRFTunerLingoRetTunerSeekRssi = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x10),
	RTRFTunerLingoSetTunerSeekRssi = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x11),
	RTRFTunerLingoTunerSeekStart = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x12),
	RTRFTunerLingoTunerSeekDone = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x13),
	RTRFTunerLingoGetTunerStatus = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x14),
	RTRFTunerLingoRetTunerStatus = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x15),
	RTRFTunerLingoGetStatusNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x16),
	RTRFTunerLingoRetStatusNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x17),
	RTRFTunerLingoSetStatusNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x18),
	RTRFTunerLingoStatusChangeNotify = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x19),
	RTRFTunerLingoGetRdsReadyStatus = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x1A),
	RTRFTunerLingoRetRdsReadyStatus = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x1B),
	RTRFTunerLingoGetRdsData = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x1C),
	RTRFTunerLingoRetRdsData = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x1D),
	RTRFTunerLingoGetRdsNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x1E),
	RTRFTunerLingoRetRdsNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x1F),
	RTRFTunerLingoSetRdsNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x20),
	RTRFTunerLingoRdsReadyNotify = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x21),
	RTRFTunerLingoGetHDProgramServiceCount = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x25),
	RTRFTunerLingoRetHDProgramServiceCount = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x26),
	RTRFTunerLingoGetHDProgramService = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x27),
	RTRFTunerLingoRetHDProgramService = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x28),
	RTRFTunerLingoSetHDProgramService = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x29),
	RTRFTunerLingoGetHDDataReadyStatus = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x2A),
	RTRFTunerLingoRetHDDataReadyStatus = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x2B),
	RTRFTunerLingoGetHDData = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x2C),
	RTRFTunerLingoRetHDData = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x2D),
	RTRFTunerLingoGetHDDataNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x2E),
	RTRFTunerLingoRetHDDataNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x2F),
	RTRFTunerLingoSetHDDataNotifyMask = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x30),
	RTRFTunerLingoHDDataReadyNotify = RT_CMD_LINGO_ID(RTRFTunerLingo, 0x31),
};

enum {
	RTAccessoryEqualizerLingoAccessoryAck = RT_CMD_LINGO_ID(RTAccessoryEqualizerLingo, 0x00),
	RTAccessoryEqualizerLingoGetCurrentEQIndex = RT_CMD_LINGO_ID(RTAccessoryEqualizerLingo, 0x01),
	RTAccessoryEqualizerLingoRetCurrentEQIndex = RT_CMD_LINGO_ID(RTAccessoryEqualizerLingo, 0x02),
	RTAccessoryEqualizerLingoSetCurrentEQIndex = RT_CMD_LINGO_ID(RTAccessoryEqualizerLingo, 0x03),
	RTAccessoryEqualizerLingoGetEQSettingCount = RT_CMD_LINGO_ID(RTAccessoryEqualizerLingo, 0x04),
	RTAccessoryEqualizerLingoRetEQSettingCount = RT_CMD_LINGO_ID(RTAccessoryEqualizerLingo, 0x05),
	RTAccessoryEqualizerLingoGetEQIndexName = RT_CMD_LINGO_ID(RTAccessoryEqualizerLingo, 0x06),
	RTAccessoryEqualizerLingoRetEQIndexName = RT_CMD_LINGO_ID(RTAccessoryEqualizerLingo, 0x07),
};

enum {
	RTSportsLingoAccessoryAck = RT_CMD_LINGO_ID(RTSportsLingo, 0x00),
	RTSportsLingoGetAccessoryVersion = RT_CMD_LINGO_ID(RTSportsLingo, 0x01),
	RTSportsLingoRetAccessoryVersion = RT_CMD_LINGO_ID(RTSportsLingo, 0x02),
	RTSportsLingoGetAccessoryCaps = RT_CMD_LINGO_ID(RTSportsLingo, 0x03),
	RTSportsLingoRetAccessoryCaps = RT_CMD_LINGO_ID(RTSportsLingo, 0x04),
	RTSportsLingoiPodAck = RT_CMD_LINGO_ID(RTSportsLingo, 0x80),
	RTSportsLingoGetiPodCaps = RT_CMD_LINGO_ID(RTSportsLingo, 0x83),
	RTSportsLingoRetiPodCaps = RT_CMD_LINGO_ID(RTSportsLingo, 0x84),
	RTSportsLingoGetUserIndex = RT_CMD_LINGO_ID(RTSportsLingo, 0x85),
	RTSportsLingoRetUserIndex = RT_CMD_LINGO_ID(RTSportsLingo, 0x86),
	RTSportsLingoGetUserData = RT_CMD_LINGO_ID(RTSportsLingo, 0x88),
	RTSportsLingoRetUserData = RT_CMD_LINGO_ID(RTSportsLingo, 0x89),
	RTSportsLingoSetUserData = RT_CMD_LINGO_ID(RTSportsLingo, 0x8A),
};

enum {
	RTDigitalAudioLingoAccessoryAck = RT_CMD_LINGO_ID(RTDigitalAudioLingo, 0x00),
	RTDigitalAudioLingoiPodAck = RT_CMD_LINGO_ID(RTDigitalAudioLingo, 0x01),
	RTDigitalAudioLingoGetAccessorySampleRateCaps = RT_CMD_LINGO_ID(RTDigitalAudioLingo, 0x02),
	RTDigitalAudioLingoRetAccessorySampleRateCaps = RT_CMD_LINGO_ID(RTDigitalAudioLingo, 0x03),
	RTDigitalAudioLingoTrackNewAudioAttributes = RT_CMD_LINGO_ID(RTDigitalAudioLingo, 0x04),
	RTDigitalAudioLingoSetVideoDelay = RT_CMD_LINGO_ID(RTDigitalAudioLingo, 0x05),
};

enum {
	RTTestLingoGetModelString = RT_CMD_LINGO_ID(RTTestLingo, 0x3C),
	RTTestLingoRetModelString = RT_CMD_LINGO_ID(RTTestLingo, 0x3D),
};

enum {
	RTStorageLingoiPodAck = RT_CMD_LINGO_ID(RTStorageLingo, 0x00),
	RTStorageLingoGetiPodCaps = RT_CMD_LINGO_ID(RTStorageLingo, 0x01),
	RTStorageLingoRetiPodCaps = RT_CMD_LINGO_ID(RTStorageLingo, 0x02),
	RTStorageLingoRetiPodFileHandle = RT_CMD_LINGO_ID(RTStorageLingo, 0x04),
	RTStorageLingoWriteiPodFileData = RT_CMD_LINGO_ID(RTStorageLingo, 0x07),
	RTStorageLingoCloseiPodFile = RT_CMD_LINGO_ID(RTStorageLingo, 0x08),
	RTStorageLingoGetiPodFreeSpace = RT_CMD_LINGO_ID(RTStorageLingo, 0x10),
	RTStorageLingoRetiPodFreeSpace = RT_CMD_LINGO_ID(RTStorageLingo, 0x11),
	RTStorageLingoOpeniPodFeatureFile = RT_CMD_LINGO_ID(RTStorageLingo, 0x12),
	RTStorageLingoAccessoryAck = RT_CMD_LINGO_ID(RTStorageLingo, 0x80),
	RTStorageLingoGetAccessoryCaps = RT_CMD_LINGO_ID(RTStorageLingo, 0x81),
	RTStorageLingoRetAccessoryCaps = RT_CMD_LINGO_ID(RTStorageLingo, 0x82),
};

enum {
	RTiPodOutLingoiPodAck = RT_CMD_LINGO_ID(RTiPodOutLingo, 0x00),
	RTiPodOutLingoGetiPodOutOptions = RT_CMD_LINGO_ID(RTiPodOutLingo, 0x01),
	RTiPodOutLingoRetiPodOutOptions = RT_CMD_LINGO_ID(RTiPodOutLingo, 0x02),
	RTiPodOutLingoSetiPodOutOptions = RT_CMD_LINGO_ID(RTiPodOutLingo, 0x03),
	RTiPodOutLingoAccessoryStateChangeEvent = RT_CMD_LINGO_ID(RTiPodOutLingo, 0x04),
	RTiPodOutLingoAccessoryVideoScreenInfo = RT_CMD_LINGO_ID(RTiPodOutLingo, 0x06),
};

enum {
	RTLocationLingoAccessoryAck = RT_CMD_LINGO_ID(RTLocationLingo, 0x00),
	RTLocationLingoGetAccessoryCaps = RT_CMD_LINGO_ID(RTLocationLingo, 0x01),
	RTLocationLingoRetAccessoryCaps = RT_CMD_LINGO_ID(RTLocationLingo, 0x02),
	RTLocationLingoGetAccessoryControl = RT_CMD_LINGO_ID(RTLocationLingo, 0x03),
	RTLocationLingoRetAccessoryControl = RT_CMD_LINGO_ID(RTLocationLingo, 0x04),
	RTLocationLingoSetAccessoryControl = RT_CMD_LINGO_ID(RTLocationLingo, 0x05),
	RTLocationLingoGetAccessoryData = RT_CMD_LINGO_ID(RTLocationLingo, 0x06),
	RTLocationLingoRetAccessoryData = RT_CMD_LINGO_ID(RTLocationLingo, 0x07),
	RTLocationLingoSetAccessoryData = RT_CMD_LINGO_ID(RTLocationLingo, 0x08),
	RTLocationLingoAsyncAccessoryData = RT_CMD_LINGO_ID(RTLocationLingo, 0x09),
	RTLocationLingoiPodAck = RT_CMD_LINGO_ID(RTLocationLingo, 0x80),
};

